# Generated by Django 3.1.5 on 2021-02-24 13:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='costs2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='costs3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='product2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sales.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='product3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sales.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='unit_sold2',
            field=models.DecimalField(decimal_places=0, help_text='max_digits = 9', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='order',
            name='unit_sold3',
            field=models.DecimalField(decimal_places=0, help_text='max_digits = 9', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
