# Generated by Django 3.1.5 on 2021-02-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='summary',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
