# Generated by Django 3.1.5 on 2021-02-20 16:37

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20210220_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='costs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='unit_sold',
            field=models.DecimalField(decimal_places=0, help_text='max_digits = 9', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
        ),
    ]
