# Generated by Django 3.1.5 on 2021-02-21 03:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20210221_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='costs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='unit_sold',
            field=models.DecimalField(decimal_places=0, help_text='max_digits = 9', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
